### ISSUE TITLE
tests: Stop hardcoding the number of cores

### ISSUE THREAD

**Issue by pmav99** [brey/pyPoseidon#22]
Hardcoding the number of cores is suboptimal. It makes it difficult to develop on low end machines (up to 4 cores) and is wasting time on higher end machines (4+ cores are available).

A reasonable default is to use the maximum number of cores minus one or two. E.g.

``` python
import multiprocessing

NCORES = max(1, multiprocessing.cpu_count() - 1)
```

Alternatively, the number of cores could be specified via an ENV variable, but not sure that something like this is that much useful at the moment.

The files that need to be updated can be found with:
``` 
ag --python ncores
```

**Comment by brey** [comment]
Done with 01b817af4f9c4d68702191a0a0972510debd7697
