### ISSUE TITLE
tests: Move tests to the outer directory

### ISSUE THREAD

**Issue by pmav99** [brey/pyPoseidon#23]
The best python framework is pytest. In order to make usage of its test runner the test suite should be structured according to its own [conventions](https://docs.pytest.org/en/reorganize-docs/new-docs/user/naming_conventions.html) (which we already do).

Nevertheless, it is also a good idea to keep the test suite outside the proper package ([docs](https://docs.pytest.org/en/stable/goodpractices.html#choosing-a-test-layout-import-rules)). Among other things, this makes it easier to grep the source code. E.g.

```
# search for `ncores` in `pyPoseidon` and `tests` respectively.
ag ncores pyPoseidon
ag ncores tests
```

I will make a pull request that moves the tests to a separate `tests` directory. @brey even if the CI passes do not merge this before making sure that you don't have changes in the tests in your local repo. If you do merge it you will have to deal with the conflicts afterwards.

**Comment by brey** [comment]
Now with the new tagged release, I guess it is a good time to do this.
