### ISSUE TITLE
Remove azure-pipelines

### ISSUE THREAD

**Issue by pmav99** [brey/pyPoseidon#35]
As soon as we are satisfied with the github actions setup, we could consider removing the azure pipelines from the project

ideally, we should keep both so that we are not coupled to a specific service, but we probably lack the resources to maintain both at the same time.

**Comment by brey** [comment]
I agree. Github actions are more integrated and they are the same backend anyway.

**Comment by brey** [comment]
We need to name appropriately the `yaml` files because they name the badges on README.

**Comment by brey** [comment]
Also... do you know how we can add a badge for coverage? It came bundled with azure but maybe there is another way..

**Comment by pmav99** [comment]
> We need to name appropriately the yaml files because they name the badges on README.

Rename as you see fit :)

> Also... do you know how we can add a badge for coverage? It came bundled with azure but maybe there is another way..

I haven't set it up. Something like this will probably do

https://github.com/marketplace/actions/coveralls-python

**Comment by brey** [comment]
> > We need to name appropriately the yaml files because they name the badges on README.
> 
> Rename as you see fit :)
> 
Is the 'pip' name consistent? I assume this is the CI for the pip installation. 

> > Also... do you know how we can add a badge for coverage? It came bundled with azure but maybe there is another way..
> 
> I haven't set it up. Something like this will probably do
> 
> https://github.com/marketplace/actions/coveralls-python

Thanks

**Comment by brey** [comment]
done with 1bb786c
