### ISSUE TITLE
Consider moving `dem.nc` to "misc"

### ISSUE THREAD

**Issue by pmav99** [brey/pyPoseidon#36]
`dem.nc` is currently located within `tests/data`. nevertheless it is also being used in `jigsaw.py`: 
https://github.com/brey/pyPoseidon/blob/4ab9963dc1f2f5c59a07cba0e948c7560ebd24f8/pyPoseidon/jigsaw.py#L143

If it is not part of the tests I think we should consider moving it to `misc`. 

This is the file in question
https://github.com/brey/pyPoseidon/blob/4ab9963dc1f2f5c59a07cba0e948c7560ebd24f8/pyPoseidon/tests/data/dem.nc

**Comment by brey** [comment]
Resolved with af67c8937b12c0cc1989731808dba0c508c8cdd1. The `dem.nc` dependency in `jigsaw.py` was not necessary.
